### ISSUE TITLE
RDKit failures if molgrid is imported first

### ISSUE THREAD

**Issue by RMeli** [gnina/libmolgrid#65]
I encountered an odd incompatibility between `molgrid` and `rdkit` which seems to depend on the order of import statements. I installed `molgrid` using `pip` in a `conda` environment where `rdkit` has been installed from the `conda-forge` channel.

---

The following snippet works as expected:
```python
from rdkit import Chem
from rdkit.Chem import AllChem

m = Chem.MolFromSmiles('C1CCC1OC')
m2 = Chem.AddHs(m)
cids = AllChem.EmbedMultipleConfs(m2, numConfs=2)
```

---

If `molgrid` is imported before `rdkit`
```python
import molgrid
from rdkit import Chem
from rdkit.Chem import AllChem

m = Chem.MolFromSmiles('C1CCC1OC')
m2 = Chem.AddHs(m)
cids = AllChem.EmbedMultipleConfs(m2, numConfs=2)
```
I get the following failure on the last line (`EmbedMultipleConfs` call):
```
TypeError: No to_python (by-value) converter found for C++ type: std::vector<int, std::allocator<int> >
```

---

The error does not appear if `molgrid` is imported after `rdkit`:
```python
from rdkit import Chem
from rdkit.Chem import AllChem
import molgrid

m = Chem.MolFromSmiles('C1CCC1OC')
m2 = Chem.AddHs(m)
cids = AllChem.EmbedMultipleConfs(m2, numConfs=2)
```

---

`conda` environment to reproduce the issue:
```yaml
name: rdkit-molgrid
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - ipython
  - pip

  - rdkit=2021.03.3
  - cudatoolkit=11.1
  - pytorch

  - pip:
    - molgrid==0.2.1
```
